export const DELETING_TRIP = "DELETING_TRIP";
export const TRIP_DELETED_SUCCESSFULLY = "TRIP_DELETED_SUCCESSFULLY";
export const TRIP_DELETING_FAILED = "TRIP_DELETING_FAILED";
export const TRIP_EDITED_SUCCESSFULLY = "TRIP_EDITED_SUCCESSFULLY";
export const EDITING_TRIP = "EDITING_TRIP";
export const TRIP_EDITING_FAILED = "TRIP_EDITING_FAILED";
export const TRIP_CREATION_FAILED = "TRIP_CREATION_FAILED";

export const CREATING_TRIP = "CREATING_TRIP";
export const TRIP_CREATED_SUCCESSFULLY = "TRIP_CREATED_SUCCESSFULLY";

export const LIKE_ADDED_SUCCESSFULLY = "LIKE_ADDED_SUCCESSFULLY";
export const REMOVING_LIKE = "REMOVING_LIKE";
export const REMOVE_LIKE_FAILED = "REMOVE_LIKE_FAILED";
export const REMOVED_LIKE_SUCCESSFULLY = "REMOVED_LIKE_SUCCESSFULLY";
export const ADDING_LIKE_FAILED = "ADDING_LIKE_FAILED";
export const ADDING_LIKE = "ADDING_LIKE";

export const USER_LOGIN_START = "USER_LOGIN_START";
export const USER_LOGIN_SUCCESSFULLY = "USER_LOGIN_SUCCESSFULLY";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_REGISTER_START = "USER_REGISTER_START";
export const USER_REGISTERED_SUCCESSFULLY = "USER_REGISTERED_SUCCESSFULLY";
export const USER_REGISTER_FAIL = "USER_REGISTERED_SUCCESSFULLY";
export const LOADING_CURRENT_USER = "LOADING_CURRENT_USER";
export const USER_LOADED_SUCCESSFULLY = "USER_LOADED_SUCCESSFULLY";
export const USER_LOADED_FAIL = "USER_LOADED_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";
export const LOAD_USER_DATA = "LOAD_USER_DATA";
export const USER_FETCHED_SUCCESSFULLY = "USER_FETCHED_SUCCESSFULLY";
export const LOADING_USER_FAILED = "LOADING_USER_FAILED";

export const CLEAR_USER = "CLEAR_USER";
export const CLEAR_TRIP = "CLEAR_TRIP";
export const CLEAR_ERRORS = "CLEAR ERRORS";

export const POSTING_COMMENT = "POSTING_COMMENT";
export const COMMENT_POSTED_SUCCESSFULLY = "COMMENT_POSTED_SUCCESSFULLY";
export const POSTING_COMMENT_FAILED = "POSTING_COMMENT_FAILED";

export const LOAD_SINGLE_TRIP = "LOAD_SINGLE_TRIP";
export const LOADING_SINGLE_TRIP_FAILED = "LOADING_SINGLE_TRIP_FAILED";

export const DEFAULT_ERROR = "DEFAULT_ERROR";

export const LOAD_TRIPS = "LOAD_TRIPS";
export const LOAD_USER_TRIPS = "LOAD_USER_TRIPS";
export const LOADING_TRIPS_FAILED = "LOADING_TRIPS_FAILED";
export const LOAD_USER_TRIPS_FAILED = "LOAD_USER_TRIPS_FAILED";
export const TRIPS_FETCHED_SUCCESSFULLY = "TRIPS_FETCHED_SUCCESSFULLY";
export const SINGLE_TRIP_FETCHED_SUCCESSFULLY =
  "SINGLE_TRIP_FETCHED_SUCCESSFULLY";
export const FETCHING_USER_TRIPS_SUCCESSFULLY =
  "FETCHING_USER_TRIPS_SUCCESSFULLY";
