export const TRIPS_FETCHED_SUCCESSFULLY = "TRIPS_FETCHED_SUCCESSFULLY";
export const SINGLE_TRIP_FETCHED_SUCCESSFULLY =
  "SINGLE_TRIP_FETCHED_SUCCESSFULLY";
export const FETCH_SINGLE_TRIP = "FETCH_SINGLE_TRIP";
export const FETCHING_USER_TRIPS_SUCCESSFULLY =
  "FETCHING_USER_TRIPS_SUCCESSFULLY";
export const DELETE_TRIP = "DELETE_TRIP";
export const TRIP_EDITED_SUCCESSFULLY = "TRIP_EDITED_SUCCESSFULLY";
export const EDITING_TRIP = "EDITING_TRIP";
export const TRIP_CREATION_FAILED = "TRIP_CREATION_FAILED";
export const CREATING_TRIP = "CREATING_TRIP";
export const ADD_LIKE = "ADD_LIKE";

export const USER_LOGIN = "USER_LOGIN";
export const USER_REGISTER = "USER_REGISTER";
export const USER_LOADED = "USER_LOADED";
export const USER_LOGOUT = "USER_LOGOUT";
export const FETCH_USER = "FETCH_USER";
export const CLEAR_USER = "CLEAR_USER";

export const CLEAR_TRIP = "CLEAR_TRIP";

export const ADD_COMMENT = "ADD_COMMENT";
export const ADDING_LIKE_FAILED = "ADDING_LIKE_FAILED";
export const LIKE_ADDED_SUCCESSFULLY = "LIKE_ADDED_SUCCESSFULLY";
export const ADDING_LIKE = "ADDING_LIKE";
export const REMOVE_LIKE = "REMOVE_LIKE";

export const CLEAR_ERRORS = "CLEAR ERRORS";
export const USER_LOADED_FAIL = "USER_LOADED_FAIL";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const FETCH_TRIPS_FAIL = "FETCH_TRIPS_FAIL";
export const FETCH_SINGLE_TRIP_FAIL = "FETCH_SINGLE_TRIP_FAILED";
export const DEFAULT_ERROR = "DEFAULT_ERROR";

export const LOAD_SINGLE_TRIP = "LOAD_SINGLE_TRIP";
export const LOAD_TRIPS = "LOAD_TRIPS";
export const LOAD_USER_TRIPS = "LOAD_USER_TRIPS";
export const LOADING_TRIPS_FAILED = "LOADING_TRIPS_FAILED";
export const LOADING_SINGLE_TRIP_FAILED = "LOADING_SINGLE_TRIP_FAILED";
export const LOAD_USER_DATA = "LOAD_USER_DATA";
export const LOADING_CURRENT_USER = "LOADING_CURRENT_USER";
export const LOAD_USER_TRIPS_FAILED = "LOAD_USER_TRIPS_FAILED";
