export const DELETING_TRIP = "DELETING_TRIP";
export const TRIP_DELETED_SUCCESSFULLY = "TRIP_DELETED_SUCCESSFULLY";
export const TRIP_DELETING_FAILED = "TRIP_DELETING_FAILED";
export const TRIP_EDITED_SUCCESSFULLY = "TRIP_EDITED_SUCCESSFULLY";
export const EDITING_TRIP = "EDITING_TRIP";
export const TRIP_EDITING_FAILED = "TRIP_EDITING_FAILED";
export const TRIP_CREATION_FAILED = "TRIP_CREATION_FAILED";

export const CREATING_TRIP = "CREATING_TRIP";
export const TRIP_CREATED_SUCCESSFULLY = "TRIP_CREATED_SUCCESSFULLY";

export const CLEAR_TRIP = "CLEAR_TRIP";
export const CLEAR_TRIPS = "CLEAR_TRIPS";

export const LOAD_TRIPS = "LOAD_TRIPS";
export const LOAD_USER_TRIPS = "LOAD_USER_TRIPS";
export const LOADING_TRIPS_FAILED = "LOADING_TRIPS_FAILED";
export const LOAD_USER_TRIPS_FAILED = "LOAD_USER_TRIPS_FAILED";
export const TRIPS_FETCHED_SUCCESSFULLY = "TRIPS_FETCHED_SUCCESSFULLY";
export const SINGLE_TRIP_FETCHED_SUCCESSFULLY =
  "SINGLE_TRIP_FETCHED_SUCCESSFULLY";
export const FETCHING_USER_TRIPS_SUCCESSFULLY =
  "FETCHING_USER_TRIPS_SUCCESSFULLY";

export const POSTING_COMMENT = "POSTING_COMMENT";
export const COMMENT_POSTED_SUCCESSFULLY = "COMMENT_POSTED_SUCCESSFULLY";
export const POSTING_COMMENT_FAILED = "POSTING_COMMENT_FAILED";

export const LOAD_SINGLE_TRIP = "LOAD_SINGLE_TRIP";
export const LOADING_SINGLE_TRIP_FAILED = "LOADING_SINGLE_TRIP_FAILED";
