version: "3.7"
services:
  database:
    image: postgres:alpine
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nwt_database
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - database
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: mmilet01@fesb.hr
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped

volumes:
  postgres-data:
